### ISSUE TITLE
Fatal signal 6 on samsung devices

### ISSUE THREAD

**Issue by kirilamenski** [sephiroth74/android-target-tooltip#129]
When I try to show tooltip via:
```java
public void showTooltip() {
        Tooltip.Builder tooltipBuilder = new Tooltip.Builder(102)
                .anchor(view, Tooltip.Gravity.TOP)
                .closePolicy(new Tooltip.ClosePolicy()
                        .insidePolicy(false, false)
                        .outsidePolicy(false, false), 30000)
                .typeface(typeface)
                .text(string)
                .withArrow(true)
                .actionBarSize(0)
                .withOverlay(false)
                .withStyleId(style);

        tooltipBuilder.floatingAnimation(Tooltip.AnimationBuilder.DEFAULT);

        Tooltip.TooltipView view = Tooltip.make(getContext(), tooltipBuilder.build());
        view.show();
}
```
the app crashed on line ```view.show(); ``` with following exception:
```java
A/zygote64: java_vm_ext.cc:504] JNI DETECTED ERROR IN APPLICATION: GetStringUTFChars received NULL jstring
A/zygote64: java_vm_ext.cc:504]     in call to GetStringUTFChars
A/zygote64: java_vm_ext.cc:504]     from int android.webkit.WebViewFactory.nativeLoadWithRelroFile(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.ClassLoader)
A/zygote64: java_vm_ext.cc:504] "main" prio=5 tid=1 Runnable
A/zygote64: java_vm_ext.cc:504]   | group="main" sCount=0 dsCount=0 flags=0 obj=0x7424eb88 self=0x72b6ec0a00
A/zygote64: java_vm_ext.cc:504]   | sysTid=32586 nice=-10 cgrp=default sched=0/0 handle=0x72bc1689c8
A/zygote64: java_vm_ext.cc:504]   | state=R schedstat=( 5690390837 95349079 1456 ) utm=516 stm=53 core=5 HZ=100
A/zygote64: java_vm_ext.cc:504]   | stack=0x7fe71d9000-0x7fe71db000 stackSize=8MB
A/zygote64: java_vm_ext.cc:504]   | held mutexes= "mutator lock"(shared held)
A/zygote64: java_vm_ext.cc:504]   native: #00 pc 000000000008e614  /system/lib64/libart.so (???)
A/zygote64: java_vm_ext.cc:504]   native: #01 pc 0000000000085de8  /system/lib64/libart.so (???)
A/zygote64: java_vm_ext.cc:504]   native: #02 pc 00000000000859e0  /system/lib64/libart.so (???)
A/zygote64: java_vm_ext.cc:504]   native: #03 pc 0000000000085e60  /system/lib64/libart.so (???)
A/zygote64: java_vm_ext.cc:504]   native: #04 pc 00000000000e2ab0  /system/lib64/libart.so (???)
A/zygote64: java_vm_ext.cc:504]   native: #05 pc 00000000000e20e8  /system/lib64/libart.so (???)
A/zygote64: java_vm_ext.cc:504]   native: #06 pc 00000000000e0a78  /system/lib64/libart.so (???)
A/zygote64: java_vm_ext.cc:504]   native: #07 pc 00000000000e9c9c  /system/lib64/libart.so (???)
A/zygote64: java_vm_ext.cc:504]   native: #08 pc 000000000000100c  /system/lib64/libwebviewchromium_loader.so (???)
A/zygote64: java_vm_ext.cc:504]   native: #09 pc 000000000004fa0c  /system/framework/arm64/boot-framework.oat (Java_android_webkit_WebViewFactory_nativeLoadWithRelroFile__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_ClassLoader_2+284)
A/zygote64: java_vm_ext.cc:504]   at android.webkit.WebViewFactory.nativeLoadWithRelroFile(Native method)
A/zygote64: java_vm_ext.cc:504]   at android.webkit.WebViewFactory.loadNativeLibrary(WebViewFactory.java:705)
A/zygote64: java_vm_ext.cc:504]   at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:412)
A/zygote64: java_vm_ext.cc:504]   at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:211)
A/zygote64: java_vm_ext.cc:504]   - locked <0x06a8a063> (a java.lang.Object)
A/zygote64: java_vm_ext.cc:504]   at android.webkit.WebView.getFactory(WebView.java:2467)
A/zygote64: java_vm_ext.cc:504]   at android.webkit.WebView.findAddress(WebView.java:1738)
A/zygote64: java_vm_ext.cc:504]   at android.text.util.Linkify.gatherMapLinks(Linkify.java:769)
A/zygote64: java_vm_ext.cc:504]   at android.text.util.Linkify.addLinks(Linkify.java:472)
A/zygote64: java_vm_ext.cc:504]   at android.widget.TextView.setText(TextView.java:5936)
A/zygote64: java_vm_ext.cc:504]   at android.widget.TextView.setText!(Native method)
A/zygote64: java_vm_ext.cc:504]   at android.widget.TextView.setText(TextView.java:5849)
A/zygote64: java_vm_ext.cc:504]   at android.widget.TextView.<init>(TextView.java:1991)
A/zygote64: java_vm_ext.cc:504]   at android.widget.TextView.<init>(TextView.java:1129)
A/zygote64: java_vm_ext.cc:504]   at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:87)
A/zygote64: java_vm_ext.cc:504]   at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:83)
A/zygote64: java_vm_ext.cc:504]   at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:177)
A/zygote64: java_vm_ext.cc:504]   at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:102)
A/zygote64: java_vm_ext.cc:504]   at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
A/zygote64: java_vm_ext.cc:504]   at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
A/zygote64: java_vm_ext.cc:504]   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
A/zygote64: java_vm_ext.cc:504]   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
A/zygote64: java_vm_ext.cc:504]   at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
A/zygote64: java_vm_ext.cc:504]   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
A/zygote64: java_vm_ext.cc:504]   at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
A/zygote64: java_vm_ext.cc:504]   - locked <0x063ca460> (a java.lang.Object[])
A/zygote64: java_vm_ext.cc:504]   at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
A/zygote64: java_vm_ext.cc:504]   at it.sephiroth.android.library.tooltip.Tooltip$TooltipViewImpl.initializeView(Tooltip.java:792)
A/zygote64: java_vm_ext.cc:504]   at it.sephiroth.android.library.tooltip.Tooltip$TooltipViewImpl.onAttachedToWindow(Tooltip.java:665)
A/zygote64: java_vm_ext.cc:504]   at android.view.View.dispatchAttachedToWindow(View.java:18623)
A/zygote64: java_vm_ext.cc:504]   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3520)
A/zygote64: java_vm_ext.cc:504]   at android.view.ViewGroup.addViewInner(ViewGroup.java:5162)
A/zygote64: java_vm_ext.cc:504]   at android.view.ViewGroup.addView(ViewGroup.java:4953)
A/zygote64: java_vm_ext.cc:504]   at android.view.ViewGroup.addView(ViewGroup.java:4925)
A/zygote64: java_vm_ext.cc:504]   at it.sephiroth.android.library.tooltip.Tooltip$TooltipViewImpl.show(Tooltip.java:494)
A/zygote64: java_vm_ext.cc:504]   at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
A/zygote64: java_vm_ext.cc:504]   at android.view.View.performClick(View.java:6897)
A/zygote64: java_vm_ext.cc:504]   at android.view.View.performClick!(Native method)
A/zygote64: java_vm_ext.cc:504]   at android.widget.TextView.performClick(TextView.java:12693)
A/zygote64: java_vm_ext.cc:504]   at android.view.View$PerformClick.run(View.java:26101)
A/zygote64: java_vm_ext.cc:504]   at android.os.Handler.handleCallback(Handler.java:789)
A/zygote64: java_vm_ext.cc:504]   at android.os.Handler.dispatchMessage(Handler.java:98)
A/zygote64: java_vm_ext.cc:504]   at android.os.Looper.loop(Looper.java:164)
A/zygote64: java_vm_ext.cc:504]   at android.app.ActivityThread.main(ActivityThread.java:6944)
A/zygote64: java_vm_ext.cc:504]   at java.lang.reflect.Method.invoke(Native method)
A/zygote64: java_vm_ext.cc:504]   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
A/zygote64: java_vm_ext.cc:504]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
A/zygote64: java_vm_ext.cc:504]
A/zygote64: runtime.cc:508] Runtime aborting...
A/zygote64: runtime.cc:508]
A/zygote64: runtime.cc:516] JNI DETECTED ERROR IN APPLICATION: GetStringUTFChars received NULL jstring
A/zygote64: runtime.cc:516]     in call to GetStringUTFChars
A/zygote64: runtime.cc:516]     from int android.webkit.WebViewFactory.nativeLoadWithRelroFile(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.ClassLoader)
A/zygote64: runtime.cc:516] "main" prio=5 tid=1 Runnable
A/zygote64: runtime.cc:516]   | group="main" sCount=0 dsCount=0 flags=0 obj=0x7424eb88 self=0x72b6ec0a00
A/zygote64: runtime.cc:516]   | sysTid=32586 nice=-10 cgrp=default sched=0/0 handle=0x72bc1689c8
A/zygote64: runtime.cc:516]   | state=R schedstat=( 5690390837 95349079 1456 ) utm=516 stm=53 core=5 HZ=100
A/zygote64: runtime.cc:516]   | stack=0x7fe71d9000-0x7fe71db000 stackSize=8MB
A/zygote64: runtime.cc:516]   | held mutexes= "mutator lock"(shared held)
A/zygote64: runtime.cc:516]   native: #00 pc 000000000008e614  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:516]   native: #01 pc 0000000000085de8  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:516]   native: #02 pc 00000000000859e0  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:516]   native: #03 pc 0000000000085e60  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:516]   native: #04 pc 00000000000e2ab0  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:516]   native: #05 pc 00000000000e20e8  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:516]   native: #06 pc 00000000000e0a78  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:516]   native: #07 pc 00000000000e9c9c  /system/lib64/libart.so (???)
A/zygote64: runtime.cc:516]   native: #08 pc 000000000000100c  /system/lib64/libwebviewchromium_loader.so (???)
A/zygote64: runtime.cc:516]   native: #09 pc 000000000004fa0c  /system/framework/arm64/boot-framework.oat (Java_android_webkit_WebViewFactory_nativeLoadWithRelroFile__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_ClassLoader_2+284)
A/zygote64: runtime.cc:516]   at android.webkit.WebViewFactory.nativeLoadWithRelroFile(Native method)
A/zygote64: runtime.cc:516]   at android.webkit.WebViewFactory.loadNativeLibrary(WebViewFactory.java:705)
A/zygote64: runtime.cc:516]   at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:412)
A/zygote64: runtime.cc:516]   at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:211)
A/zygote64: runtime.cc:516]   - locked <0x06a8a063> (a java.lang.Object)
A/zygote64: runtime.cc:516]   at android.webkit.WebView.getFactory(WebView.java:2467)
A/zygote64: runtime.cc:516]   at android.webkit.WebView.findAddress(WebView.java:1738)
A/zygote64: runtime.cc:516]   at android.text.util.Linkify.gatherMapLinks(Linkify.java:769)
A/zygote64: runtime.cc:516]   at android.text.util.Linkify.addLinks(Linkify.java:472)
A/zygote64: runtime.cc:516]   at android.widget.TextView.setText(TextView.java:5936)
A/zygote64: runtime.cc:516]   at android.widget.TextView.setText!(Native method)
A/zygote64: runtime.cc:516]   at android.widget.TextView.setText(TextView.java:5849)
A/zygote64: runtime.cc:516]   at android.widget.TextView.<init>(TextView.java:1991)
A/zygote64: runtime.cc:516]   at android.widget.TextView.<init>(TextView.java:1129)
A/zygote64: runtime.cc:516]   at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:87)
A/zygote64: runtime.cc:516]   at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:83)
A/zygote64: runtime.cc:516]   at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:177)
A/zygote64: runtime.cc:516]   at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:102)
A/zygote64: runtime.cc:516]   at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
A/zygote64: runtime.cc:516]   at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
A/zygote64: runtime.cc:516]   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
A/zygote64: runtime.cc:516]   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
A/zygote64: runtime.cc:516]   at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
A/zygote64: runtime.cc:516]   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
A/zygote64: runtime.cc:516]   at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
A/zygote64: runtime.cc:516]   - locked <0x063ca460> (a java.lang.Object[])
A/zygote64: runtime.cc:516]   at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
A/zygote64: runtime.cc:516]   at it.sephiroth.android.library.tooltip.Tooltip$TooltipViewImpl.initializeView(Tooltip.java:792)
A/zygote64: runtime.cc:516]   at it.sephiroth.android.library.tooltip.Tooltip$TooltipViewImpl.onAttachedToWindow(Tooltip.java:665)
A/zygote64: runtime.cc:516]   at android.view.View.dispatchAttachedToWindow(View.java:18623)
A/zygote64: runtime.cc:516]   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3520)
A/zygote64: runtime.cc:516]   at android.view.ViewGroup.addViewInner(ViewGroup.java:5162)
A/zygote64: runtime.cc:516]   at android.view.ViewGroup.addView(ViewGroup.java:4953)
A/zygote64: runtime.cc:516]   at android.view.ViewGroup.addView(ViewGroup.java:4925)
A/zygote64: runtime.cc:516]   at it.sephiroth.android.library.tooltip.Tooltip$TooltipViewImpl.show(Tooltip.java:494)
A/zygote64: runtime.cc:516]   at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
A/zygote64: runtime.cc:516]   at android.view.View.performClick(View.java:6897)
A/zygote64: runtime.cc:516]   at android.view.View.performClick!(Native method)
A/zygote64: runtime.cc:516]   at android.widget.TextView.performClick(TextView.java:12693)
A/zygote64: runtime.cc:516]   at android.view.View$PerformClick.run(View.java:26101)
A/zygote64: runtime.cc:516]   at android.os.Handler.handleCallback(Handler.java:789)
A/zygote64: runtime.cc:516]   at android.os.Handler.dispatchMessage(Handler.java:98)
A/zygote64: runtime.cc:516]   at android.os.Looper.loop(Looper.java:164)
A/zygote64: runtime.cc:516]   at android.app.ActivityThread.main(ActivityThread.java:6944)
A/zygote64: runtime.cc:516]   at java.lang.reflect.Method.invoke(Native method)
A/zygote64: runtime.cc:516]   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
A/zygote64: runtime.cc:516]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
A/zygote64: runtime.cc:516]
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 32586 (ia***.dev)
```

it happens only for samsung s7, s8 (I don't know about s9) and does not happen in s10.
On the any other devices it works fine.

The version of lib is 1.3.15, I know it is pretty old version, but on new version 2.0.3 it happens too.
I would be very grateful if you help me to avoid it on the old version, because at the moment I can not update to the latest version.

Regards!

**Comment by kirilamenski** [comment]
https://stackoverflow.com/questions/51885709/sudden-error-on-mobileads-initialize-using-android-studio

Found a solution. Updating the Android WebView has solved the problem.
But I don’t understand how the library is related to webview?
