### ISSUE TITLE
getColor throws exception -> Target SDK 23

### ISSUE THREAD

**Issue by pbertsch** [sephiroth74/android-target-tooltip#36]
In the **TooltipTextDrawable** Class line **42** thows an exception 

`int backgroundColor = theme.getColor(styleable.TooltipLayout_ttlm_backgroundColor, 0);
`
It looks like an issue by not using the **ContextCompat Class**

04-04 16:20:41.200 16638-16638/com.bansi.pagomovil E/InputEventReceiver: Exception dispatching input event.
04-04 16:20:41.200 16638-16638/com.bansi.pagomovil E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
04-04 16:20:41.220 16638-16638/com.bansi.pagomovil E/MessageQueue-JNI: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 24: TypedValue{t=0x3/d=0x8dd "res/drawable-xxhdpi-v4/list_divider_holo_light.9.png" a=1 r=0x108048d}
                                                                           at android.content.res.TypedArray.getColor(TypedArray.java:447)
                                                                           at it.sephiroth.android.library.tooltip.TooltipTextDrawable.<init>(TooltipTextDrawable.java:42)
                                                                           at it.sephiroth.android.library.tooltip.Tooltip$TooltipViewImpl.<init>(Tooltip.java:477)
                                                                           at it.sephiroth.android.library.tooltip.Tooltip.make(Tooltip.java:71)

**Comment by wangbourne** [comment]
same thing happen on me

I tried to call:

Tooltip.make(
                getActivity(),
                new Tooltip.Builder()
                        .anchor(getActivity().findViewById(R.id.help_button), Tooltip.Gravity.BOTTOM)
                        .fitToScreen(true)
                        .closePolicy(Tooltip.ClosePolicy.TOUCH_INSIDE_CONSUME, 10000)
                        .text("BOTTOM. Touch outside to dismiss the tooltip")
                        .withArrow(true)
                        .maxWidth(300)
                        .withStyleId(R.style.ToolTipLayoutDefaultStyle_Custom1)
                        .build()
        ).show();


and get the error of 

java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x1c/d=0xff33b5e5 a=1 r=0x1060012}
                                                                                at android.content.res.TypedArray.getColor(TypedArray.java:447)

**Comment by sephiroth74** [comment]
Can you also reproduce this with the sample app? Because it's working correctly here.

**Comment by wangbourne** [comment]
The exception happen at the line of :
alpha = array.getColor(fadeOut, 0);

in the following code block:

TypedArray array = context.getTheme().obtainStyledAttributes(defStyleResId, styleable.TooltipOverlay);

        for(int fadeIn = 0; fadeIn < array.getIndexCount(); ++fadeIn) {
            int fadeOut = array.getIndex(fadeIn);
            int alpha;
            if(fadeOut == styleable.TooltipOverlay_android_color) {
                alpha = array.getColor(fadeOut, 0);
                this.mOuterPaint.setColor(alpha);
                this.mInnerPaint.setColor(alpha);


Obvious, it is because that context.getTheme().obtainStyledAttributes does not include an attribute of color

**Comment by milneti** [comment]
I have this issue as well...

Was this going to be resolved? I attempted to add the attributes wangbourne described, but it is not solving the issue. Unless I am doing it incorrectly?

I attempted to extend the default:
<style name="MyTooltipStyle" parent="ToolTipOverlayDefaultStyle">
        <item name="colorAccent">#0092ff</item>
        <item name="colorPrimary">#ffcc00</item>
        <item name="colorPrimaryDark">#ff6600</item>
    </style>

and add: withStyleId(R.style.MyTooltipStyle) to my builder
