### ISSUE TITLE
java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x0/d=0x0}

### ISSUE THREAD

**Issue by firasalkafri** [sephiroth74/android-target-tooltip#65]

**Comment by medozeus** [comment]
Seems you didnt use them or you use this library in widnowManger so add Them to your Context

**Comment by kevalpatel2106** [comment]
@medozeus @firasalkafri I am also getting the same issue.  Here is my code where I displayed tooltip.

`    Tooltip.make(MainActivity.this,
                            new Tooltip.Builder()
                                    .anchor(v, Tooltip.Gravity.BOTTOM)
                                    .closePolicy(new Tooltip.ClosePolicy()
                                            .insidePolicy(true, false)
                                            .outsidePolicy(true, false), 3000)
                                    .activateDelay(800)
                                    .showDelay(300)
                                    .text(strToDisplay)
                                    .typeface(Typeface.DEFAULT)
                                    .withArrow(true)
                                    .withOverlay(true)
                                    .floatingAnimation(Tooltip.AnimationBuilder.DEFAULT)
                                    .build()
                    ).show();`

But I am getting error: 

> java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x3/d=0x1d1 "res/drawable/ic_menu_moreoverflow_material.xml" a=1 r=0x10803d6}
                      at android.content.res.TypedArray.getColor(TypedArray.java:447)
                      at it.sephiroth.android.library.tooltip.TooltipOverlayDrawable.<init>(TooltipOverlayDrawable.java:54)
                      at it.sephiroth.android.library.tooltip.TooltipOverlay.init(TooltipOverlay.java:25)
                      at it.sephiroth.android.library.tooltip.TooltipOverlay.<init>(TooltipOverlay.java:37)
                      at it.sephiroth.android.library.tooltip.Tooltip$TooltipViewImpl.<init>(Tooltip.java:472)
                      at it.sephiroth.android.library.tooltip.Tooltip.make(Tooltip.java:71)
                      at com.cwa.eltekiq8quadselector.MainActivity$5.onClick(MainActivity.java:218)
                      at android.view.View.performClick(View.java:5198)
                      at android.view.View$PerformClick.run(View.java:21147)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by medozeus** [comment]
@kevalpatel2106  did you use the code in activity or in window manger you must have an theme in your context and seems you don't have theme  #fb.com/deluxezeus998

**Comment by kevalpatel2106** [comment]
@medozeus I used the tooltip in activity. I did not add theme to my  style file.

**Comment by medozeus** [comment]
@kevalpatel2106  just try appcompatactivity theme

**Comment by michelelacorte** [comment]
News about this issue?

**Comment by medozeus** [comment]
add them to your activity or Context

**Comment by michelelacorte** [comment]
@medozeus I've do this!

**Comment by yozhik** [comment]
Hi! I have the same issue. Have anyone solved it? Using API level 19. Thanks.

```
Fatal Exception: java.lang.RuntimeException
Failed to resolve attribute at index 96
android.content.res.TypedArray.getColor (TypedArray.java:401)
androidx.appcompat.widget.AppCompatTextView.<init> (AppCompatTextView.java:79)
it.sephiroth.android.library.xtooltip.Tooltip.preparePopup (Tooltip.kt:309)
it.sephiroth.android.library.xtooltip.Tooltip.show (Tooltip.kt:624)
......
Uo.handleMessage (PG:64)
```


```
Fatal Exception: java.lang.RuntimeException
Failed to resolve attribute at index 96
android.content.res.TypedArray.getColor (TypedArray.java:401)
androidx.appcompat.widget.AppCompatTextView.<init> (AppCompatTextView.java:79)
it.sephiroth.android.library.xtooltip.Tooltip.preparePopup (Tooltip.kt:309)
it.sephiroth.android.library.xtooltip.Tooltip.show (Tooltip.kt:624)
```

**Comment by anhanh11001** [comment]
> Hi! I have the same issue. Have anyone solved it? Using API level 19. Thanks.
> @michelelacorte have you solved it?
> 
> ```
> Fatal Exception: java.lang.RuntimeException
> Failed to resolve attribute at index 96
> android.content.res.TypedArray.getColor (TypedArray.java:401)
> androidx.appcompat.widget.AppCompatTextView.<init> (AppCompatTextView.java:79)
> it.sephiroth.android.library.xtooltip.Tooltip.preparePopup (Tooltip.kt:309)
> it.sephiroth.android.library.xtooltip.Tooltip.show (Tooltip.kt:624)
> ......
> Uo.handleMessage (PG:64)
> ```

I'm having the same issue
