### ISSUE TITLE
android.view.InflateException: Binary XML file line #8: Error inflating class TextView

### ISSUE THREAD

**Issue by geekvxyz** [sephiroth74/android-target-tooltip#78]
Hello sephiroth74：
`<TextView
        android:id="@android:id/text1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:autoLink="all"
        android:clipToPadding="false"
        android:textAppearance="?android:attr/textAppearanceSmallInverse" />`

 "android:autoLink"-->This property may cause an error on some devices.

Error log：
Attempt to invoke interface method 'java.lang.String[] com.mediatek.common.util.IWebProtocolNames.getWebProtocolNames()' on a null object reference

thinks！

**Comment by xMikeTx** [comment]
Also experiencing this on a Lenovo A5000

`Fatal Exception: android.view.InflateException: Binary XML file line #8: Error inflating class TextView
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at it.sephiroth.android.library.tooltip.Tooltip$TooltipViewImpl.initializeView(Tooltip.java:792)
       at it.sephiroth.android.library.tooltip.Tooltip$TooltipViewImpl.onAttachedToWindow(Tooltip.java:665)
       at android.view.View.dispatchAttachedToWindow(View.java:13573)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2831)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:4043)
       at android.view.ViewGroup.addView(ViewGroup.java:3857)
       at android.view.ViewGroup.addView(ViewGroup.java:3833)
       at it.sephiroth.android.library.tooltip.Tooltip$TooltipViewImpl.show(Tooltip.java:494)
       at com.tractive.android.gps.features.map.view.ui.views.SpeedDialButtonView$expandButtons$$inlined$apply$lambda$1.onAnimationEnd(SpeedDialButtonView.java:154)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1089)
       at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:666)
       at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:682)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:795)`
