### ISSUE TITLE
How to use Custom Layout with tooltip

### ISSUE THREAD

**Issue by AsifNazir** [sephiroth74/android-target-tooltip#85]
I am getting exception while adding custom layout with provided method e.g

withCustomView(R.layout.popup_layout) where R.layout.popup.layout) is custom layout

Exception:

09-11 01:58:12.126 5075-5075/it.sephiroth.android.library.mymodule.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                         Process: it.sephiroth.android.library.mymodule.app, PID: 5075
                                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                                             at it.sephiroth.android.library.tooltip.Tooltip$TooltipViewImpl.initializeView(Tooltip.java:796)
                                                                                             at it.sephiroth.android.library.tooltip.Tooltip$TooltipViewImpl.onAttachedToWindow(Tooltip.java:665)
                                                                                             at android.view.View.dispatchAttachedToWindow(View.java:13662)
                                                                                             at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2837)
                                                                                             at android.view.ViewGroup.addViewInner(ViewGroup.java:4049)
                                                                                             at android.view.ViewGroup.addView(ViewGroup.java:3863)
                                                                                             at android.view.ViewGroup.addView(ViewGroup.java:3839)
                                                                                             at it.sephiroth.android.library.tooltip.Tooltip$TooltipViewImpl.show(Tooltip.java:494)
                                                                                             at it.sephiroth.android.library.mymodule.app.MainActivity2$Fragment1.onClick(MainActivity2.java:284)
                                                                                             at android.view.View.performClick(View.java:4827)
                                                                                             at android.view.View$PerformClick.run(View.java:20235)
                                                                                             at android.os.Handler.handleCallback(Handler.java:810)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                             at android.os.Looper.loop(Looper.java:209)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5900)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1005)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)

**Comment by MaximilianFrick** [comment]
Would like to have this functionality as well.
As far as i could see is that it expects a `TextView` as CustomView so any layout which is anything else than a TextView will not work here.

**Comment by AsifNazir** [comment]
Will be waiting when this functionality can be added. ?
